import { Box, FormControl, IconButton, MenuItem, Select, Slider, Stack, Tooltip, Typography } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import Forward10Icon from '@mui/icons-material/Forward10';
import Replay10Icon from '@mui/icons-material/Replay10';
import PauseIcon from '@mui/icons-material/Pause';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import FullscreenIcon from '@mui/icons-material/Fullscreen';
import FullscreenExitIcon from '@mui/icons-material/FullscreenExit';
import VolumeUpIcon from '@mui/icons-material/VolumeUp';
import VolumeOffIcon from '@mui/icons-material/VolumeOff';
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import type { PlaybackQuality } from '@/api';

export interface PlayerControlsProps { playing: boolean; current: number; duration: number; volume: number; muted: boolean; fullscreen: boolean; quality: PlaybackQuality; qualities: PlaybackQuality[]; title: string; episode?: string; onToggle:()=>void; onSeek:(seconds:number)=>void; onSkip:(seconds:number)=>void; onVolume:(value:number)=>void; onMute:()=>void; onFullscreen:()=>void; onQuality:(value:PlaybackQuality)=>void; onBack:()=>void; onStats:()=>void }
const labels:Record<PlaybackQuality,string>={AUTO:'Automático',ORIGINAL:'Original','4K':'4K','1080P_HIGH':'1080p Alta','1080P':'1080p','720P':'720p','480P':'480p'};
const time=(seconds:number)=>{if(!Number.isFinite(seconds))return '0:00';const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=Math.floor(seconds%60);return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
export function PlayerControls(p:PlayerControlsProps){return <Box sx={{position:'absolute',inset:0,p:{xs:1.5,sm:3},pt:{xs:'max(12px, env(safe-area-inset-top))',sm:3},pb:{xs:'max(12px, env(safe-area-inset-bottom))',sm:3},display:'flex',flexDirection:'column',justifyContent:'space-between',color:'#fff',background:'linear-gradient(180deg,rgba(0,0,0,.68),transparent 25%,transparent 65%,rgba(0,0,0,.9))'}}>
  <Stack direction="row" justifyContent="space-between" alignItems="center"><Stack direction="row" spacing={{xs:.5,sm:1.5}} alignItems="center" sx={{minWidth:0}}><IconButton sx={{color:'inherit'}} onClick={p.onBack} aria-label="Voltar"><ArrowBackIcon/></IconButton><Box sx={{minWidth:0}}><Typography fontWeight={700} noWrap>{p.title}</Typography>{p.episode?<Typography variant="body2" noWrap sx={{opacity:.8}}>{p.episode}</Typography>:null}</Box></Stack><Tooltip title="Informações de streaming"><IconButton sx={{color:'inherit'}} onClick={p.onStats}><InfoOutlinedIcon/></IconButton></Tooltip></Stack>
  <Box><Slider aria-label="Progresso" value={Math.min(p.current,p.duration||0)} min={0} max={p.duration||1} onChange={(_e,v)=>p.onSeek(v as number)} sx={{color:'primary.light',mb:{xs:-.5,sm:0}}}/><Stack direction="row" justifyContent="space-between" alignItems="center"><Stack direction="row" alignItems="center" spacing={{xs:0,sm:1}}><IconButton sx={{color:'inherit'}} onClick={p.onToggle} aria-label={p.playing?'Pausar':'Reproduzir'}>{p.playing?<PauseIcon/>:<PlayArrowIcon/>}</IconButton><IconButton sx={{color:'inherit'}} onClick={()=>p.onSkip(-10)} aria-label="Voltar 10 segundos"><Replay10Icon/></IconButton><IconButton sx={{color:'inherit'}} onClick={()=>p.onSkip(10)} aria-label="Avançar 10 segundos"><Forward10Icon/></IconButton><IconButton sx={{color:'inherit'}} onClick={p.onMute} aria-label={p.muted?'Ativar som':'Silenciar'}>{p.muted?<VolumeOffIcon/>:<VolumeUpIcon/>}</IconButton><Slider aria-label="Volume" value={p.muted?0:p.volume} min={0} max={1} step={.05} onChange={(_e,v)=>p.onVolume(v as number)} sx={{width:90,color:'#fff',display:{xs:'none',md:'block'}}}/><Typography variant="body2" sx={{ml:{xs:.5,sm:0},whiteSpace:'nowrap'}}>{time(p.current)}<Box component="span" sx={{display:{xs:'none',sm:'inline'}}}> / {time(p.duration)}</Box></Typography></Stack><Stack direction="row" alignItems="center" spacing={{xs:0,sm:1.5}}><FormControl size="small" sx={{display:{xs:'none',sm:'inline-flex'}}}><Select value={p.quality} onChange={e=>p.onQuality(e.target.value as PlaybackQuality)} sx={{color:'#fff','.MuiOutlinedInput-notchedOutline':{borderColor:'rgba(255,255,255,.4)'},'.MuiSvgIcon-root':{color:'#fff'}}}>{p.qualities.map(q=><MenuItem key={q} value={q}>{labels[q]}</MenuItem>)}</Select></FormControl><IconButton sx={{color:'inherit'}} onClick={p.onFullscreen} aria-label="Tela cheia">{p.fullscreen?<FullscreenExitIcon/>:<FullscreenIcon/>}</IconButton></Stack></Stack></Box>
</Box>}
