import { Box, Button, Card, CardContent, Chip, Divider, Skeleton, Stack, Tab, Tabs, Typography } from '@mui/material';
import RefreshIcon from '@mui/icons-material/Refresh';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { api, type MediaDetails, type MediaType } from '@/api';
import { EmptyState } from '@/components/states/EmptyState';
import { FavoriteButton } from '../components/FavoriteButton';
import { MediaPosterCard } from '../components/MediaPosterCard';
import { EpisodeCard } from '../components/EpisodeCard';
import { formatFileSize, formatRuntime, imageUrl } from '../utils';
import { beginPlayback } from '@/features/playback/session';

export default function MediaDetailsPage({ type }: { type: MediaType }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const queryClient = useQueryClient();
  const details = useQuery({ queryKey: ['media', 'details', id], queryFn: () => type === 'TV_SHOW' ? api.media.tvDetails(id) : api.media.details(id), enabled: Boolean(id) });
  const seasons = useQuery({ queryKey: ['media', 'seasons', id], queryFn: () => api.media.seasons(id), enabled: type === 'TV_SHOW' && Boolean(id) });
  const selected = Number(params.get('season') ?? seasons.data?.[0]?.seasonNumber ?? 0);
  const episodes = useQuery({ queryKey: ['media', 'episodes', id, selected], queryFn: () => api.media.episodes(id, selected), enabled: type === 'TV_SHOW' && Boolean(id) && Boolean(seasons.data?.length) });
  const similar = useQuery({ queryKey: ['media', 'similar', id], queryFn: () => api.media.similar(id), enabled: Boolean(details.data) });
  const watching = useQuery({ queryKey: ['playback', 'continue'], queryFn: api.playback.continueWatching });
  const refresh = useMutation({ mutationFn: () => api.media.refreshMetadata(id), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['media', 'details', id] }) });
  if (details.isLoading) return <Stack spacing={3}><Skeleton variant="rounded" height={360} /><Skeleton height={150} /></Stack>;
  if (!details.data) return <EmptyState title="Conteúdo não encontrado" action={{ label: 'Voltar', onClick: () => navigate(-1) }} />;
  const item = details.data;
  return <Stack spacing={{ xs: 4, md: 6 }}>
    <Hero item={item} onRefresh={() => refresh.mutate()} refreshing={refresh.isPending} />
    {type === 'MOVIE' && item.files?.[0] ? <PlaybackActions progress={watching.data?.items.find(p => p.mediaItemId === item.id && !p.episodeId)?.positionMs} onPlay={async (restart) => { const value = await beginPlayback({ mediaItemId: item.id, mediaFileId: item.files?.[0]?.id, resumeFrom: restart ? 0 : undefined }); navigate(`/player/${value.response.sessionId}`); }} /> : null}
    <Section title="Sinopse"><Typography color="text.secondary" sx={{ maxWidth: 900, lineHeight: 1.75 }}>{item.overview || 'Sinopse não disponível.'}</Typography></Section>
    {type === 'TV_SHOW' ? <Section title="Temporadas e episódios">{seasons.isLoading ? <Skeleton height={56} /> : seasons.data?.length ? <><Tabs value={selected} onChange={(_e, value: number) => setParams({ season: String(value) })} variant="scrollable" scrollButtons="auto" sx={{ mb: 3 }}>{seasons.data.map((season) => <Tab key={season.id} value={season.seasonNumber} label={season.seasonNumber === 0 ? 'Especiais' : `${season.name} (${season.episodeCount})`} />)}</Tabs><Stack spacing={2}>{episodes.isLoading ? Array.from({ length: 4 }, (_, i) => <Skeleton key={i} variant="rounded" height={150} />) : episodes.data?.items.map((episode) => <EpisodeCard key={episode.id} episode={episode} progress={watching.data?.items.find(p => p.episodeId === episode.id)?.percentage} onPlay={episode.mediaFileId ? async () => { const value = await beginPlayback({ mediaItemId: item.id, mediaFileId: episode.mediaFileId, episodeId: episode.id }); navigate(`/player/${value.response.sessionId}`); } : undefined} />)}</Stack></> : <EmptyState title="Nenhuma temporada encontrada" />}</Section> : null}
    {item.cast.length ? <Section title="Elenco"><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))', gap: 3 }}>{item.cast.slice(0, 12).map((person) => <Box key={person.id}><Box sx={{ aspectRatio: '2/3', borderRadius: 2, overflow: 'hidden', bgcolor: (t) => t.tokens.surfaceContainerHigh }}>{person.profilePath ? <Box component="img" src={imageUrl(person.profilePath)} alt="" loading="lazy" sx={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : null}</Box><Typography fontWeight={600} noWrap sx={{ mt: 1 }}>{person.name}</Typography><Typography variant="body2" color="text.secondary" noWrap>{person.character}</Typography></Box>)}</Box></Section> : null}
    <Section title="Informações"><Metadata item={item} /></Section>
    {item.files?.length ? <Section title="Arquivos"><Stack spacing={2}>{item.files.map((file) => <Card key={file.id} variant="outlined"><CardContent><Typography fontWeight={650}>{file.filename}</Typography><Typography variant="body2" color="text.secondary" sx={{ wordBreak: 'break-all' }}>{file.relativePath}</Typography><Stack direction="row" spacing={1} sx={{ mt: 2 }}><Chip size="small" label={formatFileSize(file.fileSize)} /><Chip size="small" label={file.extension?.toUpperCase() ?? 'Arquivo'} /><Chip size="small" label={file.identificationStatus ?? '—'} /></Stack></CardContent></Card>)}</Stack></Section> : null}
    {similar.data?.items.length ? <Section title="Você também pode gostar"><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(6, minmax(130px, 1fr))', gap: 3, overflowX: 'auto' }}>{similar.data.items.map((media) => <MediaPosterCard key={media.id} item={media} />)}</Box></Section> : null}
  </Stack>;
}

function Hero({ item, onRefresh, refreshing }: { item: MediaDetails; onRefresh: () => void; refreshing: boolean }) {
  return <Box sx={{ position: 'relative', minHeight: { xs: 480, sm: 380 }, mx: { xs: -2, md: -4 }, mt: { xs: -2, md: -4 }, overflow: 'hidden', bgcolor: (t) => t.tokens.surfaceContainerHigh }}>
    {item.backdropPath ? <Box component="img" src={imageUrl(item.backdropPath, 'original')} alt="" sx={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', opacity: .38 }} /> : null}<Box sx={{ position: 'absolute', inset: 0, background: (t) => `linear-gradient(90deg, ${t.tokens.surface} 0%, transparent 75%), linear-gradient(0deg, ${t.tokens.surface} 0%, transparent 55%)` }} />
    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={{ xs: 2, sm: 4 }} alignItems={{ xs: 'stretch', sm: 'flex-end' }} justifyContent={{ xs: 'flex-end', sm: 'flex-start' }} sx={{ position: 'relative', minHeight: 'inherit', p: { xs: 2, sm: 3, md: 6 }, pt: { xs: 16, md: 10 } }}><Box sx={{ width: 180, aspectRatio: '2/3', borderRadius: 2, overflow: 'hidden', flexShrink: 0, display: { xs: 'none', sm: 'block' }, bgcolor: (t) => t.tokens.surfaceContainerHighest }}>{item.posterPath ? <Box component="img" src={imageUrl(item.posterPath)} alt="" sx={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : null}</Box><Box><Typography variant="h1" sx={{ fontSize: { xs: 32, md: 44 } }}>{item.title}</Typography>{item.tagline ? <Typography color="text.secondary" sx={{ mt: 1, fontStyle: 'italic' }}>{item.tagline}</Typography> : null}<Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap sx={{ mt: 2 }}><Chip label={item.year ?? '—'} /><Chip label={item.mediaType === 'MOVIE' ? formatRuntime(item.runtime) : `${item.numberOfSeasons ?? 0} temporadas`} />{item.rating !== undefined ? <Chip label={`★ ${item.rating.toFixed(1)}`} /> : null}{item.genres.map((g) => <Chip key={g.id} variant="outlined" label={g.name} />)}</Stack><Stack direction="row" alignItems="center" spacing={1} flexWrap="wrap" useFlexGap sx={{ mt: 3 }}><FavoriteButton id={item.id} isFavorite={item.isFavorite} /><Typography sx={{ fontSize: { xs: 14, sm: 16 } }}>{item.isFavorite ? 'Remover da Minha Lista' : 'Adicionar à Minha Lista'}</Typography><Button startIcon={<RefreshIcon />} onClick={onRefresh} disabled={refreshing}>{refreshing ? 'Atualizando…' : 'Atualizar metadados'}</Button></Stack></Box></Stack>
  </Box>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <Box component="section"><Typography variant="h2" sx={{ mb: 2 }}>{title}</Typography>{children}</Box>; }
function PlaybackActions({ progress, onPlay }: { progress?: number; onPlay: (restart: boolean) => void }) { const time = progress ? new Date(progress).toISOString().slice(progress >= 3_600_000 ? 11 : 14, 19) : ''; return <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5}><Button fullWidth variant="contained" size="large" startIcon={<PlayArrowIcon />} onClick={() => onPlay(false)}>{progress ? `Continuar ${time}` : 'Reproduzir'}</Button>{progress ? <Button fullWidth size="large" onClick={() => onPlay(true)}>Recomeçar</Button> : null}</Stack>; }
function Metadata({ item }: { item: MediaDetails }) { const entries = [['Título original', item.originalTitle], [item.mediaType === 'MOVIE' ? 'Data de lançamento' : 'Data de estreia', item.releaseDate ?? item.firstAirDate], ['Duração', item.mediaType === 'MOVIE' ? formatRuntime(item.runtime) : undefined], ['Status', item.status], ['Idioma original', item.originalLanguage], ['Rating', item.rating?.toFixed(1)], ['Votos', item.voteCount?.toLocaleString('pt-BR')], ['Popularidade', item.popularity?.toFixed(1)], ['TMDB ID', String(item.tmdbId)], ['Última atualização', new Date(item.metadataFetchedAt).toLocaleString('pt-BR')]]; return <Card variant="outlined"><CardContent>{entries.filter(([, value]) => value).map(([label, value], index) => <Box key={label}>{index ? <Divider sx={{ my: 1.5 }} /> : null}<Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={0.5}><Typography color="text.secondary">{label}</Typography><Typography textAlign={{ sm: 'right' }}>{value}</Typography></Stack></Box>)}</CardContent></Card>; }
